# Uncomment this to enable unstable features
#unstable_features = true

binop_separator = "Back"                # unstable
brace_style = "PreferSameLine"          # unstable
color = "Always"                        # unstable
combine_control_expr = false            # unstable
condense_wildcard_suffixes = true       # unstable
control_brace_style = "ClosingNextLine" # unstable
edition = "2021"
fn_args_layout = "Compressed"
format_code_in_doc_comments = true      # unstable
format_strings = true                   # unstable
hard_tabs = false
hex_literal_case = Lower                # unstable
#ignore = [] # unstable
imports_layout = "Mixed"                # unstable
indent_style = "Visual"                 # unstable (maybe keep as "Block")
match_arm_leading_pipes = Never
match_block_trailing_comma = true
imports_granularity = One               # unstable
newline_style = "Native"
normalize_comments = true               # unstable
normalize_doc_attributes = true         # unstable
remove_nested_parens = true
reorder_impl_items = true               # unstable
reorder_imports = true
group_imports = StdExternalCrate        # unstable
space_after_colon = true                # unstable
space_before_colon = false              # unstable
spaces_around_ranges = false            # unstable
struct_lit_single_line = false          # unstable
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
trailing_comma = "Always"               # unstable
trailing_semicolon = true               # unstable
type_punctuation_density = "Wide"       # unstable
use_field_init_shorthand = false
#use_small_heuristics = Off
where_single_line = true                # unstable
wrap_comments = true                    # unstable
